### ISSUE TITLE
Updated docs?

### ISSUE THREAD

**Issue by com6056** [yknx4/librecov#203]
Found this project after exploring https://github.com/danhper/opencov, awesome you are keeping it going!

Are there any updated docs for getting a deployment of this going though? Seems like quite a few changes have been made but no updates to the README. Right now I'm struggling to get the initial setup done since `mix` isn't in the Docker image so I can't run `mix ecto.setup`.

Thanks!

**Comment by tnarik** [comment]
In addition, running via docker is not possible as the image is unavailable at the moment.

**Comment by prologic** [comment]
I've pushed a Docker build of this to my Docker Hub account at [prologic/librecov](https://hub.docker.com/repository/docker/prologic/librecov)

**Comment by prologic** [comment]
I wasn't able to get this working 😢 I just keep getting "502 Bad Gateway" despite no errors

Here's my `docker-compose.yml`:

```yaml
---
version: "3.8"

services:
  db:
    image: postgres:9.5
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: '<redacted>'
    networks:
      - librecov
    deploy:
      replicas: 1

  setup:
    image: prologic/librecov:dev
    command: mix ecto.setup
    environment:
      DATABASE_URL: "ecto://postgres:<redacted>@db/opencov_prod?ssl=false"
      SECRET_KEY_BASE: "<redacted>"
    networks:
      - librecov
    deploy:
      restart_policy:
        condition: none
    
  librecov:
    image: prologic/librecov
    environment:
      PORT: "4000"
      DATABASE_URL: "postgres://postgres:<redacted>@db/opencov_prod?ssl=false"
      SECRET_KEY_BASE: "<redacted>"
      LIBRECOV_HOST: "cov.mydomain.com"
      LIBRECOV_CDN_HOST: "cov.mydomain.com"
    networks:
      - traefik
      - librecov
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.coverage_librecov.loadbalancer.server.port=4000"
        - "traefik.http.routers.coverage_librecov.rule=Host(`cov.mydomain.com`)"
        - "traefik.http.routers.coverage_librecov.priority=2"
      restart_policy:
        condition: on-failure

networks:
  traefik:
    external: true
  librecov:
    driver: overlay

volumes:
  db:
    driver: local
```

I also pushed a modified version of the [Dockerfile](/Dockerfile) as [prologic/librecov:dev](https://hub.docker.com/repository/docker/prologic/librecov) as this app doesn't seem to do its own database setup or migrations on startup, so you need to have a service (which I've called `setup`) that uses the "dev" image with all the tooling installed just to run `mix ecto:setup` 🤷‍♂️
